export  const Actions={
    TODOREQUEST:"TODOREQUEST",
    TODOSUCCESS:"TODOSUCCESS",
    TODOFAILURE:"TODOFAILURE",
    TODOPOSTREQUEST:"TODOPOSTREQUEST",
    INC:"INC",
    DEC:"DEC",
    LOGINREQUEST:"LOGINREQUEST",
    LOGINSUCCESS:"LOGINSUCCESS",
    LOGINFAILURE:"LOGINFAILURE"
}